@Library('standard-library@main') _

pipeline {
    agent {
        label 'node20'
    }
    stages{
        stage('Install bun'){
            steps{
                sh 'bun install'
                sh 'bun build'
                sleep 600
            }
        }
    }
    post {
        always {
            script{
                pga.cleanupWorkspace()
            }
        }
        unstable {
            script{
                pga.slack_webhook("web")
            }
        }
        failure{
            script{
                sshagent(credentials: ['jenkins2']) {
                    sh 'ssh  $SSH_USER_PASS@$HOST "cd /home/GuildManager/Infrastructure/scripts && ./restore-images.sh"'
                }
                pga.slack_webhook("web")
            }
        }
    }
}